### ISSUE TITLE
Help finding IMEI 

### ISSUE THREAD

**Issue by paulgbrichardson** [tinaught/appkettleapi#1]
This looks amazing!  I'm trying to remove any dependency on IFTTT now they are moving to a pay model (and the lag sucks).  The integration of my kettle is the last piece of the puzzle and this repo looks like it would solve my woes. 
However, can you please help explain how to find the kettles IMEI?

**Comment by danmed** [comment]
Would like to know this to.. Would also.. ideally.. like to know how to actually use this!

**Comment by paulgbrichardson** [comment]
I figured this out (somehow!).  Sometimes leaving things alone for a while is the best remedy.
1. Find the IP of the kettle
2. Run the python and what for the reponse.
3. The response has the IMEI within it.
4. Re-run with the correct IMEI and it worked.

Not sure why I missed the IMEI was different in the response!

**Comment by tinaught** [comment]
Thank you for the comment - I've pushed an update to facilitate more graceful discovery when run without parameters. The script broadcasts an UDP "probe" message to the network to find out the kettle IP and IMEI (if the kettle replies) so it should make it easier to find the right IP.

Thanks for flagging!
